language: c
sudo: false
dist: trusty

before_script:
  - bash ./build_libmicrohttpd.sh --compile

install: "pip install Sphinx"

script:
 - make checkstyle
 - make
# -W to turn warnings into errors
 - make -C docs SPHINXOPTS=-W dummy
 - make -C docs SPHINXOPTS=-W linkcheck

env:
  - CFLAGS="-I/tmp/libmicrohttpd_install/include" LDFLAGS="-L/tmp/libmicrohttpd_install/lib"

addons:
  apt:
    packages:
    - astyle
